version: "3"

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: school
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
  api:
    build: .
    ports:
     - 3001:3001

volumes:
  postgres: